### ISSUE TITLE
РНБ

### ISSUE THREAD

**Issue by dubinsky** [opentorah/alter-rebbe.org#2069]
От кого фотографии дела 2011?

В номенклатуре дел:
203: РО, Евр IV,                     дело  203
211: РО, фонд 152, опись 1, дело  211

Что такое "РО" в обоих делах?
Что такое "Евр IV" в деле 203?
Есть ли у дела 203 фонд и опись?

**Comment by michaelko58** [comment]
Барахович Зелман ,раввин. Письмо ко всем евреям, в Белоруссии пребывающим
Фонд 152 опись 1 дело 211 количество  листов 4.
Это то, что пришли из  RNL
Прежнее описание можем считать устаревшим

**Comment by dubinsky** [comment]
@michaelko58 как говорят у нас в америке, what the fuck does it even mean?
Я не знаю (и знать не хочу), что такое RNL,
не понимаю, что такое "прежнее описание", чего оно описание, и какая разница, каким его считать.
Мне надо что-то конкретное написать в файлах.

В ТРЕТИЙ раз спрашиваю: кому сказать спасибо за фотографии дела 211?
Что делать с "РО" в номенклатуре обоих дел? Выкинуть?
Что такое "Евр IV" в деле 203?
Есть ли у дела 203 фонд и опись?

**Comment by michaelko58** [comment]
Заказал я на сайте, деньги платил Давидов, занимайся пока делом 211, второго у нас нет. В 211 выкини все, кроме того, что я тебе прислал

**Comment by michaelko58** [comment]
Догадался, РО - отдел рукописей, можешь оставить

**Comment by dubinsky** [comment]
Это вот оставить или нет:

Описание в CAHJP: Военский К.Е. Перевод на русской послания Шнеур Залмана из Ляд к российским евреям.
Рукописная копия из Военно-ученого архива.

**Comment by dubinsky** [comment]
"РО" не хочу: это никому ничего не говорит:
могу ВМЕСТО него написать то, что ты мне скажешь - в точности.

**Comment by dubinsky** [comment]
Мне надо оба дела вставить в структуруч для этого я должен понимать, какова иерархия в этом архиве:
отдел / фонд / опись / дело? Или "Евр IV" - это какая-то новая единица деления?

**Comment by michaelko58** [comment]
Евр. - видимо отдел еврейских рукописей

**Comment by michaelko58** [comment]
Это не архив, а библиотека, потому у них немного иначе

**Comment by dubinsky** [comment]
Так описание из CAHJP выкидывать или нет?

**Comment by dubinsky** [comment]
@michaelko58  Нет ответов. Я сделал как-то. Когда будешь подчищать всю структуру, скеажешь, что не так.
